/home/matereza/PycharmProjects/damas-core/venv/bin/python /home/matereza/PycharmProjects/damas-core/py/async_cli/main_test.py
================================>>> test_read_many_element started
Traceback (most recent call last):
  File "/home/matereza/PycharmProjects/damas-core/py/async_cli/main_test.py", line 203, in <module>
    loop.run_until_complete(main(loop))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/matereza/PycharmProjects/damas-core/py/async_cli/main_test.py", line 180, in main
    await test_read_many_element(ids, 10)
  File "/home/matereza/PycharmProjects/damas-core/py/async_cli/main_test.py", line 95, in test_read_many_element
    await asyncio.gather(*tasks)
  File "/home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py", line 179, in read
    json_result = await resp.json()
  File "/home/matereza/PycharmProjects/damas-core/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('http://localhost:8090/api/read/')
Task was destroyed but it is pending!
task: <Task pending name='Task-201' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1ddaf0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-200' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1dd8b0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-199' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1dd670>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-198' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1dd430>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-197' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1dd1f0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-196' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1d4f70>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-195' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1d4d30>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-194' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1d4af0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-193' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1d48b0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-192' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1d4670>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-191' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1d4430>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-190' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1d41f0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-189' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1caf70>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-188' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1cad30>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-187' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1caaf0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-186' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1ca8b0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-185' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1ca640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-184' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1ca400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-183' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1ca1c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-182' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1c1f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-181' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1c1d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-180' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1c1ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-179' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1c1880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-178' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1c1640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-177' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1c1400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-176' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1c11c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-175' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1b8f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-174' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1b8d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-173' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1b8ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-172' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1b8880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-171' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1b8640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-170' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1b8400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-169' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1b81c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-168' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec231f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-167' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec231d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-166' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec231ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-165' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec231880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-164' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec231640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-163' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec231400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-162' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec2311c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-161' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec227f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-160' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec227d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-159' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec227ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-158' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec227880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-157' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec227640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-156' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec227400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-155' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec2271c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-154' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec21ef40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-153' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec21ed00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-152' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec21eac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-151' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec21e880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-150' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec21e640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-149' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec21e400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-148' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec21e1c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-147' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec215f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-146' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec215d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-145' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec215ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-144' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec215880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-143' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec215640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-142' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec215400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-141' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec2151c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-140' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec20ef40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-139' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec20ed00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-138' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec20eac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-137' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec20e880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-136' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec20e640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-135' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec20e400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-134' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec20e1c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-133' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec204f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-132' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec204d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-131' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec204ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-130' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec204880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-129' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec204640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-128' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec204400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-127' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec2041c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-126' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1faf40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-125' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1fad00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-124' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1faac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-123' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1fa880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-122' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1fa640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-121' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1fa400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-120' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec1fa1c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-119' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec273f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-118' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec273d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-117' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec273ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-116' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec273880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-115' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec273640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-114' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec273400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-113' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec2731c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-112' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec268f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-111' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec268d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-110' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec268ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-109' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec268880>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-108' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec268640>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-107' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec268400>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-106' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec2681c0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-105' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec261f40>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-104' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec261d00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-103' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2aec261ac0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-102' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(6, handle=<Handle BaseS....0.1', 8090))>)(), <TaskWakeupMethWrapper object at 0x7f2aec2b40a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>

Process finished with exit code 1
